<?php

namespace App;


/**
 * 非框架数据表模型
 * Class ProductsInstockShipping
 * @package App
 */
class ProductsInstockShipping extends Model
{
    //自定义表名
    protected $table = 'products_instock_shipping';
    //自定义主键
    protected $primaryKey = 'products_instock_id';
    //时间戳
    public $timestamps = false;

    /**
     * 如果自定义主键了 这个方法可以不必
     * 自定义键名
     * 隐式模型绑定除 id 以外的数据库字段
     * @return string
     */
    public function getRouteKeyName()
    {
        //return parent::getRouteKeyName(); // TODO: Change the autogenerated stub
        return 'products_instock_id';
    }

    /**
     * 获取模型的路由键值.
     *
     * @return mixed
     */
    public function getRouteKey()
    {
        return 'products_instock_id';
    }


}
